<?php
require_once('./config/config.php');
require_once('./system/addons.php');
require_once('./system/site.php');
require_once('./system/page.php');
require_once('./system/post.php');
require_once('./system/tags.php');
require_once('./system/rss.php');
?>
